use_frameworks!

platform :ios, '8.0'

target 'TLMImageTest_Example' do
  pod 'TLMImageTest', :path => '../'

  target 'TLMImageTest_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
